const TEXTS = {
  "/": {
    getTheBonus: "Get The Bonus",
    refresh: "Refresh",
    casino: "Casino",
    bonuses: "Bonuses",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Get",
    maximumAmount: "Maximum amount",
    wager: "Wager",
    bonusCode: "Bonus code",
    topCasinos: "Top Casinos",
    topCasinosWelcome: "Welcome Bonus",
    claimBonus: "Claim Bonus",
    allCasinos: "All Casino",
    allGames: "All Games",
    playNow: "Play Now",
  },
  de: {
    getTheBonus: "Bonus Erhalten",
    refresh: "Aktualisieren",
    casino: "Kasino",
    bonuses: "Boni",
    rate: "Rate",
    freeSpins: "Frei Spins",
    moreInfo: "Mehr Info",
    get: "Get",
    maximumAmount: "Maximaler Betrag",
    wager: "Wager",
    bonusCode: "Bonus-Code",
    topCasinos: "Top-Kasinos",
    topCasinosWelcome: "Willkommensbonus",
    claimBonus: "Bonus Einfordern",
    allCasinos: "Alle Kasinos",
    allGames: "Alle Spiele",
    playNow: "Jetzt Spielen",
  },
  us: {
    getTheBonus: "Get The Bonus",
    refresh: "Refresh",
    casino: "Casino",
    bonuses: "Bonuses",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Get",
    maximumAmount: "Maximum amount",
    wager: "Wager",
    bonusCode: "Bonus code",
    topCasinos: "Top Casinos",
    topCasinosWelcome: "Welcome Bonus",
    claimBonus: "Claim Bonus",
    allCasinos: "All Casino",
    allGames: "All Games",
    playNow: "Play Now",
  },
  ie: {
    getTheBonus: "Get The Bonus",
    refresh: "Refresh",
    casino: "Casino",
    bonuses: "Bonuses",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Get",
    maximumAmount: "Maximum amount",
    wager: "Wager",
    bonusCode: "Bonus code",
    topCasinos: "Top Casinos",
    topCasinosWelcome: "Welcome Bonus",
    claimBonus: "Claim Bonus",
    allCasinos: "All Casino",
    allGames: "All Games",
    playNow: "Play Now",
  },
  se: {
    getTheBonus: "Få bonusen",
    refresh: "Uppdatera",
    casino: "Kasino",
    bonuses: "Bonusar",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "Mer info",
    get: "Få",
    maximumAmount: "Maximalt belopp",
    wager: "Wager",
    bonusCode: "Bonuskod",
    topCasinos: "Topp casinon",
    topCasinosWelcome: "Välkomstbonus",
    claimBonus: "Hämta bonus",
    allCasinos: "Alla Casinon",
    allGames: "Alla Spel",
    playNow: "Spela Nu",
  },
};

function getPageKey() {
  const seg = window.location.pathname.split("/")[1];
  return TEXTS[seg] ? seg : "/";
}

export function t(key) {
  const pageKey = getPageKey();
  return TEXTS[pageKey]?.[key] ?? TEXTS["/"]?.[key] ?? key;
}
