const TEXTS = {
  "/": {
    welcomeBonus: "Welcome Bonus",
    getTheBonus: "Get The Bonus",
    refresh: "Refresh",
    casino: "Casino",
    bonuses: "Bonuses",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Get",
    maximumAmount: "Maximum amount",
    wager: "Wager",
    bonusCode: "Bonus code",
    topCasinos: "Top Casinos",
    topCasinosWelcome: "Welcome Bonus",
    claimBonus: "Claim Bonus",
    allCasinos: "All Casino",
    allGames: "All Games",
    playNow: "Play Now",
  },
  nz: {
    welcomeBonus: "Welcome Bonus",
    getTheBonus: "Get The Bonus",
    refresh: "Refresh",
    casino: "Casino",
    bonuses: "Bonuses",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Get",
    maximumAmount: "Maximum amount",
    wager: "Wager",
    bonusCode: "Bonus code",
    topCasinos: "Top Casinos",
    topCasinosWelcome: "Welcome Bonus",
    claimBonus: "Claim Bonus",
    allCasinos: "All Casino",
    allGames: "All Games",
    playNow: "Play Now",
  },
  at: {
    welcomeBonus: "Willkommensbonus",
    getTheBonus: "Bonus Erhalten",
    refresh: "Aktualisieren",
    casino: "Kasino",
    bonuses: "Boni",
    rate: "Rate",
    freeSpins: "Frei Spins",
    moreInfo: "Mehr Info",
    get: "Get",
    maximumAmount: "Maximaler Betrag",
    wager: "Wager",
    bonusCode: "Bonus-Code",
    topCasinos: "Top-Kasinos",
    topCasinosWelcome: "Willkommensbonus",
    claimBonus: "Bonus Einfordern",
    allCasinos: "Alle Kasinos",
    allGames: "Alle Spiele",
    playNow: "Jetzt Spielen",
  },
  ga: {
    welcomeBonus: "Tairiscint eisiach fáilte roimh",
    getTheBonus: "Faigh an Bónas",
    refresh: "Athnuaigh",
    casino: "Casino",
    bonuses: "Bónais",
    rate: "Ráta",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Faigh",
    maximumAmount: "Uasmhéid",
    wager: "Wager",
    bonusCode: "Cóid bónas",
    topCasinos: "Barr Casinos",
    topCasinosWelcome: "Bónas Fáilte",
    claimBonus: "Éileamh Bónas",
    allCasinos: "Gach Casino",
    allGames: "Gach Cluichí",
    playNow: "Seinn Anois",
  },
  "us": {
    welcomeBonus: "Welcome Bonus",
    getTheBonus: "Get The Bonus",
    refresh: "Refresh",
    casino: "Casino",
    bonuses: "Bonuses",
    rate: "Rate",
    freeSpins: "Free Spins",
    moreInfo: "More Info",
    get: "Get",
    maximumAmount: "Maximum amount",
    wager: "Wager",
    bonusCode: "Bonus code",
    topCasinos: "Top Casinos",
    topCasinosWelcome: "Welcome Bonus",
    claimBonus: "Claim Bonus",
    allCasinos: "All Casino",
    allGames: "All Games",
    playNow: "Play Now",
  },
  "de": {
    welcomeBonus: "Willkommensbonus",
    getTheBonus: "Bonus Erhalten",
    refresh: "Aktualisieren",
    casino: "Kasino",
    bonuses: "Boni",
    rate: "Rate",
    freeSpins: "Frei Spins",
    moreInfo: "Mehr Info",
    get: "Get",
    maximumAmount: "Maximaler Betrag",
    wager: "Wager",
    bonusCode: "Bonus-Code",
    topCasinos: "Top-Kasinos",
    topCasinosWelcome: "Willkommensbonus",
    claimBonus: "Bonus Einfordern",
    allCasinos: "Alle Kasinos",
    allGames: "Alle Spiele",
    playNow: "Jetzt Spielen",
  },
};

function getPageKey() {
  const seg = window.location.pathname.split("/")[1];
  return TEXTS[seg] ? seg : "/";
}

export function t(key) {
  const pageKey = getPageKey();
  return TEXTS[pageKey]?.[key] ?? TEXTS["/"]?.[key] ?? key;
}
